xinput_name: 10moons-pen
vendor_id: 0x08f2
product_id: 0x6811
pen:
    max_x: 4080
    max_y: 4080
    max_pressure: 2047
    resolution_x: 20
    resolution_y: 30
actions:
    pen: BTN_TOOL_PEN
    sylus: BTN_STYLUS
    pen_touch: BTN_TOUCH
    tablet_buttons:
        - KEY_LEFTCTRL+KEY_Z
        - KEY_LEFTCTRL+KEY_Y
        - KEY_RIGHTCTRL+KEY_1
        - KEY_RIGHTCTRL+KEY_5
        - KEY_UP
        - KEY_DOWN
settings:
    swap_axis: false
    swap_direction_x: true
    swap_direction_y: false
filter:
    smoothing: 0.25
    deadzone: 6
screen_mapping:
    width_percent: 100
    height_percent: 100
    x_offset_percent: 0
    y_offset_percent: 0
